package main 
//display latitude and longtitude for any given IP address

import ( "fmt"
	   "net/url"
	   "net/http"
	   )



func main () {

//fmt.Println("Please enter the IP addy"  ....do this part later
// create a new request, a new client and use Do function	
//https://mholt.github.io/json-to-go/	
//should i get the json first then convert then use gethtml to get the lat and long	

resp, err := http.Get("http://api.hostip.info/get_html.php?ip=198.252.210.32&position=true")
if err != nil {
	fmt.Println("oops, error")
} else {

safeIp := url.QueryEscape(resp )  //error cannot use resp (type *http.Response) as type string in argument to url.QueryEscape
//i tried resp string, the example is s string_
fmt.Println(safeIp)

url := fmt.Sprintf("http://api.hostip.info/get_json.php?position=true&ip=%s", safeIp)
//Sprint returns as a string instead of printing etc....why are we getting jscon/string

fmt.Println(safeIp)
}
type AutoGenerated struct {
	CountryName string `json:"country_name"`
	CountryCode string `json:"country_code"`
	City string `json:"city"`
	IP string `json:"ip"`
}

fmt.Println(CountryName, CountryCode, City, IP)

}